//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCoffee.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeeHouses
    {
        public CoffeeHouses()
        {
            this.Employees = new HashSet<Employees>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.TimeSpan> work_time_from { get; set; }
        public Nullable<System.TimeSpan> work_time_to { get; set; }
        public string contact_phone { get; set; }
        public Nullable<int> employees_count { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
