//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCoffee.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int id { get; set; }
        public string name { get; set; }
        public int coffeehouse_id { get; set; }
        public int post_id { get; set; }
        public System.DateTime works_from { get; set; }
        public int delay_count { get; set; }
        public int truancy_count { get; set; }
        public int hospital_count { get; set; }
        public Nullable<System.DateTime> vacation_start { get; set; }
        public Nullable<System.DateTime> vacation_end { get; set; }
        public bool is_works { get; set; }
    
        public virtual CoffeeHouses CoffeeHouses { get; set; }
        public virtual Posts Posts { get; set; }
    }
}
